# Initial cache for Ubuntu + GCC builds.
set(CMAKE_C_COMPILER gcc CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER g++ CACHE FILEPATH "")
set(CMAKE_CXX_STANDARD 17 CACHE STRING "")
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "")
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "")
