# Initial cache for Windows 11 + Visual Studio 2022 builds.
set(CMAKE_GENERATOR "Visual Studio 17 2022" CACHE INTERNAL "")
set(CMAKE_CXX_STANDARD 17 CACHE STRING "")
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "")
set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "")
